// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: dump/game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TournamentRound_RoundType int32

const (
	TournamentRound_TOURNAMENTROUND_ROUNDTYPE_UNSPECIFIED       TournamentRound_RoundType = 0
	TournamentRound_TOURNAMENTROUND_ROUNDTYPE_RANDOM_MATCHES    TournamentRound_RoundType = 1
	TournamentRound_TOURNAMENTROUND_ROUNDTYPE_SINGLE_ELIM_WIN_2 TournamentRound_RoundType = 2
	TournamentRound_TOURNAMENTROUND_ROUNDTYPE_ROUND_ROBIN       TournamentRound_RoundType = 3
	TournamentRound_TOURNAMENTROUND_ROUNDTYPE_TOP_N             TournamentRound_RoundType = 4
	TournamentRound_TOURNAMENTROUND_ROUNDTYPE_TIERED_TOP_N      TournamentRound_RoundType = 5
)

// Enum value maps for TournamentRound_RoundType.
var (
	TournamentRound_RoundType_name = map[int32]string{
		0: "TOURNAMENTROUND_ROUNDTYPE_UNSPECIFIED",
		1: "TOURNAMENTROUND_ROUNDTYPE_RANDOM_MATCHES",
		2: "TOURNAMENTROUND_ROUNDTYPE_SINGLE_ELIM_WIN_2",
		3: "TOURNAMENTROUND_ROUNDTYPE_ROUND_ROBIN",
		4: "TOURNAMENTROUND_ROUNDTYPE_TOP_N",
		5: "TOURNAMENTROUND_ROUNDTYPE_TIERED_TOP_N",
	}
	TournamentRound_RoundType_value = map[string]int32{
		"TOURNAMENTROUND_ROUNDTYPE_UNSPECIFIED":       0,
		"TOURNAMENTROUND_ROUNDTYPE_RANDOM_MATCHES":    1,
		"TOURNAMENTROUND_ROUNDTYPE_SINGLE_ELIM_WIN_2": 2,
		"TOURNAMENTROUND_ROUNDTYPE_ROUND_ROBIN":       3,
		"TOURNAMENTROUND_ROUNDTYPE_TOP_N":             4,
		"TOURNAMENTROUND_ROUNDTYPE_TIERED_TOP_N":      5,
	}
)

func (x TournamentRound_RoundType) Enum() *TournamentRound_RoundType {
	p := new(TournamentRound_RoundType)
	*p = x
	return p
}

func (x TournamentRound_RoundType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TournamentRound_RoundType) Descriptor() protoreflect.EnumDescriptor {
	return file_dump_game_proto_enumTypes[0].Descriptor()
}

func (TournamentRound_RoundType) Type() protoreflect.EnumType {
	return &file_dump_game_proto_enumTypes[0]
}

func (x TournamentRound_RoundType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TournamentRound_RoundType.Descriptor instead.
func (TournamentRound_RoundType) EnumDescriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{1, 0}
}

type TournamentRound_RankingType int32

const (
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_UNSPECIFIED                    TournamentRound_RankingType = 0
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_NO_RANKINGS                    TournamentRound_RankingType = 1
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_WP_SP                          TournamentRound_RankingType = 2
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_WIN_PCT_WP_SP                  TournamentRound_RankingType = 3
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_3_OF_4               TournamentRound_RankingType = 4
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_PREV_ROUND           TournamentRound_RankingType = 5
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_WP_HEADTOHEAD_TOT_PTS          TournamentRound_RankingType = 6
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_AVG_SCORE_HIGH_SCORES          TournamentRound_RankingType = 7
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_AVG_PTS_3_OF_4                 TournamentRound_RankingType = 8
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_WP_AP_SP                       TournamentRound_RankingType = 9
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_WIN_PCT_WP_AP_SP               TournamentRound_RankingType = 10
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_WP                   TournamentRound_RankingType = 11
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_AVG_WP_AP_SP                   TournamentRound_RankingType = 12
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_AVG_WP_AVG_SCORE_HIGH_SCORES   TournamentRound_RankingType = 13
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_OVERALL_SCORE_DROP_1 TournamentRound_RankingType = 14
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_AVG_PTS                        TournamentRound_RankingType = 15
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_AVG_PTS_DROP_1_OF_6            TournamentRound_RankingType = 16
	TournamentRound_TOURNAMENTROUND_RANKINGTYPE_AVG_PTS_3_OF_4_KEEP_NO_SHOW    TournamentRound_RankingType = 17
)

// Enum value maps for TournamentRound_RankingType.
var (
	TournamentRound_RankingType_name = map[int32]string{
		0:  "TOURNAMENTROUND_RANKINGTYPE_UNSPECIFIED",
		1:  "TOURNAMENTROUND_RANKINGTYPE_NO_RANKINGS",
		2:  "TOURNAMENTROUND_RANKINGTYPE_WP_SP",
		3:  "TOURNAMENTROUND_RANKINGTYPE_WIN_PCT_WP_SP",
		4:  "TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_3_OF_4",
		5:  "TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_PREV_ROUND",
		6:  "TOURNAMENTROUND_RANKINGTYPE_WP_HEADTOHEAD_TOT_PTS",
		7:  "TOURNAMENTROUND_RANKINGTYPE_AVG_SCORE_HIGH_SCORES",
		8:  "TOURNAMENTROUND_RANKINGTYPE_AVG_PTS_3_OF_4",
		9:  "TOURNAMENTROUND_RANKINGTYPE_WP_AP_SP",
		10: "TOURNAMENTROUND_RANKINGTYPE_WIN_PCT_WP_AP_SP",
		11: "TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_WP",
		12: "TOURNAMENTROUND_RANKINGTYPE_AVG_WP_AP_SP",
		13: "TOURNAMENTROUND_RANKINGTYPE_AVG_WP_AVG_SCORE_HIGH_SCORES",
		14: "TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_OVERALL_SCORE_DROP_1",
		15: "TOURNAMENTROUND_RANKINGTYPE_AVG_PTS",
		16: "TOURNAMENTROUND_RANKINGTYPE_AVG_PTS_DROP_1_OF_6",
		17: "TOURNAMENTROUND_RANKINGTYPE_AVG_PTS_3_OF_4_KEEP_NO_SHOW",
	}
	TournamentRound_RankingType_value = map[string]int32{
		"TOURNAMENTROUND_RANKINGTYPE_UNSPECIFIED":                    0,
		"TOURNAMENTROUND_RANKINGTYPE_NO_RANKINGS":                    1,
		"TOURNAMENTROUND_RANKINGTYPE_WP_SP":                          2,
		"TOURNAMENTROUND_RANKINGTYPE_WIN_PCT_WP_SP":                  3,
		"TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_3_OF_4":               4,
		"TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_PREV_ROUND":           5,
		"TOURNAMENTROUND_RANKINGTYPE_WP_HEADTOHEAD_TOT_PTS":          6,
		"TOURNAMENTROUND_RANKINGTYPE_AVG_SCORE_HIGH_SCORES":          7,
		"TOURNAMENTROUND_RANKINGTYPE_AVG_PTS_3_OF_4":                 8,
		"TOURNAMENTROUND_RANKINGTYPE_WP_AP_SP":                       9,
		"TOURNAMENTROUND_RANKINGTYPE_WIN_PCT_WP_AP_SP":               10,
		"TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_WP":                   11,
		"TOURNAMENTROUND_RANKINGTYPE_AVG_WP_AP_SP":                   12,
		"TOURNAMENTROUND_RANKINGTYPE_AVG_WP_AVG_SCORE_HIGH_SCORES":   13,
		"TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_OVERALL_SCORE_DROP_1": 14,
		"TOURNAMENTROUND_RANKINGTYPE_AVG_PTS":                        15,
		"TOURNAMENTROUND_RANKINGTYPE_AVG_PTS_DROP_1_OF_6":            16,
		"TOURNAMENTROUND_RANKINGTYPE_AVG_PTS_3_OF_4_KEEP_NO_SHOW":    17,
	}
)

func (x TournamentRound_RankingType) Enum() *TournamentRound_RankingType {
	p := new(TournamentRound_RankingType)
	*p = x
	return p
}

func (x TournamentRound_RankingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TournamentRound_RankingType) Descriptor() protoreflect.EnumDescriptor {
	return file_dump_game_proto_enumTypes[1].Descriptor()
}

func (TournamentRound_RankingType) Type() protoreflect.EnumType {
	return &file_dump_game_proto_enumTypes[1]
}

func (x TournamentRound_RankingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TournamentRound_RankingType.Descriptor instead.
func (TournamentRound_RankingType) EnumDescriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{1, 1}
}

type Game_VexProgram int32

const (
	Game_GAME_VEXPROGRAM_UNSPECIFIED Game_VexProgram = 0
	Game_GAME_VEXPROGRAM_VRC         Game_VexProgram = 10
	Game_GAME_VEXPROGRAM_VEXU        Game_VexProgram = 20
	Game_GAME_VEXPROGRAM_VEXIQ       Game_VexProgram = 30
	Game_GAME_VEXPROGRAM_VEXAI       Game_VexProgram = 40
	Game_GAME_VEXPROGRAM_RADC        Game_VexProgram = 50
	Game_GAME_VEXPROGRAM_BELL        Game_VexProgram = 60
	Game_GAME_VEXPROGRAM_TSA         Game_VexProgram = 100
)

// Enum value maps for Game_VexProgram.
var (
	Game_VexProgram_name = map[int32]string{
		0:   "GAME_VEXPROGRAM_UNSPECIFIED",
		10:  "GAME_VEXPROGRAM_VRC",
		20:  "GAME_VEXPROGRAM_VEXU",
		30:  "GAME_VEXPROGRAM_VEXIQ",
		40:  "GAME_VEXPROGRAM_VEXAI",
		50:  "GAME_VEXPROGRAM_RADC",
		60:  "GAME_VEXPROGRAM_BELL",
		100: "GAME_VEXPROGRAM_TSA",
	}
	Game_VexProgram_value = map[string]int32{
		"GAME_VEXPROGRAM_UNSPECIFIED": 0,
		"GAME_VEXPROGRAM_VRC":         10,
		"GAME_VEXPROGRAM_VEXU":        20,
		"GAME_VEXPROGRAM_VEXIQ":       30,
		"GAME_VEXPROGRAM_VEXAI":       40,
		"GAME_VEXPROGRAM_RADC":        50,
		"GAME_VEXPROGRAM_BELL":        60,
		"GAME_VEXPROGRAM_TSA":         100,
	}
)

func (x Game_VexProgram) Enum() *Game_VexProgram {
	p := new(Game_VexProgram)
	*p = x
	return p
}

func (x Game_VexProgram) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Game_VexProgram) Descriptor() protoreflect.EnumDescriptor {
	return file_dump_game_proto_enumTypes[2].Descriptor()
}

func (Game_VexProgram) Type() protoreflect.EnumType {
	return &file_dump_game_proto_enumTypes[2]
}

func (x Game_VexProgram) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Game_VexProgram.Descriptor instead.
func (Game_VexProgram) EnumDescriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2, 0}
}

type Game_MatchTimeEntry_BlockType int32

const (
	Game_MatchTimeEntry_MATCHTIMEENTRY_BLOCKTYPE_UNSPECIFIED Game_MatchTimeEntry_BlockType = 0
	Game_MatchTimeEntry_MATCHTIMEENTRY_BLOCKTYPE_TIMER_ONLY  Game_MatchTimeEntry_BlockType = 1
	Game_MatchTimeEntry_MATCHTIMEENTRY_BLOCKTYPE_AUTONOMOUS  Game_MatchTimeEntry_BlockType = 2
	Game_MatchTimeEntry_MATCHTIMEENTRY_BLOCKTYPE_DRIVER_CTRL Game_MatchTimeEntry_BlockType = 3
	Game_MatchTimeEntry_MATCHTIMEENTRY_BLOCKTYPE_PAUSE       Game_MatchTimeEntry_BlockType = 4
	Game_MatchTimeEntry_MATCHTIMEENTRY_BLOCKTYPE_PRESTART    Game_MatchTimeEntry_BlockType = 5
)

// Enum value maps for Game_MatchTimeEntry_BlockType.
var (
	Game_MatchTimeEntry_BlockType_name = map[int32]string{
		0: "MATCHTIMEENTRY_BLOCKTYPE_UNSPECIFIED",
		1: "MATCHTIMEENTRY_BLOCKTYPE_TIMER_ONLY",
		2: "MATCHTIMEENTRY_BLOCKTYPE_AUTONOMOUS",
		3: "MATCHTIMEENTRY_BLOCKTYPE_DRIVER_CTRL",
		4: "MATCHTIMEENTRY_BLOCKTYPE_PAUSE",
		5: "MATCHTIMEENTRY_BLOCKTYPE_PRESTART",
	}
	Game_MatchTimeEntry_BlockType_value = map[string]int32{
		"MATCHTIMEENTRY_BLOCKTYPE_UNSPECIFIED": 0,
		"MATCHTIMEENTRY_BLOCKTYPE_TIMER_ONLY":  1,
		"MATCHTIMEENTRY_BLOCKTYPE_AUTONOMOUS":  2,
		"MATCHTIMEENTRY_BLOCKTYPE_DRIVER_CTRL": 3,
		"MATCHTIMEENTRY_BLOCKTYPE_PAUSE":       4,
		"MATCHTIMEENTRY_BLOCKTYPE_PRESTART":    5,
	}
)

func (x Game_MatchTimeEntry_BlockType) Enum() *Game_MatchTimeEntry_BlockType {
	p := new(Game_MatchTimeEntry_BlockType)
	*p = x
	return p
}

func (x Game_MatchTimeEntry_BlockType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Game_MatchTimeEntry_BlockType) Descriptor() protoreflect.EnumDescriptor {
	return file_dump_game_proto_enumTypes[3].Descriptor()
}

func (Game_MatchTimeEntry_BlockType) Type() protoreflect.EnumType {
	return &file_dump_game_proto_enumTypes[3]
}

func (x Game_MatchTimeEntry_BlockType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Game_MatchTimeEntry_BlockType.Descriptor instead.
func (Game_MatchTimeEntry_BlockType) EnumDescriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2, 1, 0}
}

type Game_Skills_SkillsType int32

const (
	Game_Skills_SKILLS_SKILLSTYPE_UNSPECIFIED Game_Skills_SkillsType = 0
	Game_Skills_SKILLS_SKILLSTYPE_PROGRAMMING Game_Skills_SkillsType = 1
	Game_Skills_SKILLS_SKILLSTYPE_DRIVER      Game_Skills_SkillsType = 2
)

// Enum value maps for Game_Skills_SkillsType.
var (
	Game_Skills_SkillsType_name = map[int32]string{
		0: "SKILLS_SKILLSTYPE_UNSPECIFIED",
		1: "SKILLS_SKILLSTYPE_PROGRAMMING",
		2: "SKILLS_SKILLSTYPE_DRIVER",
	}
	Game_Skills_SkillsType_value = map[string]int32{
		"SKILLS_SKILLSTYPE_UNSPECIFIED": 0,
		"SKILLS_SKILLSTYPE_PROGRAMMING": 1,
		"SKILLS_SKILLSTYPE_DRIVER":      2,
	}
)

func (x Game_Skills_SkillsType) Enum() *Game_Skills_SkillsType {
	p := new(Game_Skills_SkillsType)
	*p = x
	return p
}

func (x Game_Skills_SkillsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Game_Skills_SkillsType) Descriptor() protoreflect.EnumDescriptor {
	return file_dump_game_proto_enumTypes[4].Descriptor()
}

func (Game_Skills_SkillsType) Type() protoreflect.EnumType {
	return &file_dump_game_proto_enumTypes[4]
}

func (x Game_Skills_SkillsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Game_Skills_SkillsType.Descriptor instead.
func (Game_Skills_SkillsType) EnumDescriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2, 4, 0}
}

type Game_Skills_Ranking_Type int32

const (
	Game_Skills_Ranking_RANKING_TYPE_UNSPECIFIED            Game_Skills_Ranking_Type = 0
	Game_Skills_Ranking_RANKING_TYPE_HIGH_SCORES            Game_Skills_Ranking_Type = 1
	Game_Skills_Ranking_RANKING_TYPE_HIGH_SCORE_FORMULA     Game_Skills_Ranking_Type = 2
	Game_Skills_Ranking_RANKING_TYPE_TOTAL_POINTS_RECURSIVE Game_Skills_Ranking_Type = 3
)

// Enum value maps for Game_Skills_Ranking_Type.
var (
	Game_Skills_Ranking_Type_name = map[int32]string{
		0: "RANKING_TYPE_UNSPECIFIED",
		1: "RANKING_TYPE_HIGH_SCORES",
		2: "RANKING_TYPE_HIGH_SCORE_FORMULA",
		3: "RANKING_TYPE_TOTAL_POINTS_RECURSIVE",
	}
	Game_Skills_Ranking_Type_value = map[string]int32{
		"RANKING_TYPE_UNSPECIFIED":            0,
		"RANKING_TYPE_HIGH_SCORES":            1,
		"RANKING_TYPE_HIGH_SCORE_FORMULA":     2,
		"RANKING_TYPE_TOTAL_POINTS_RECURSIVE": 3,
	}
)

func (x Game_Skills_Ranking_Type) Enum() *Game_Skills_Ranking_Type {
	p := new(Game_Skills_Ranking_Type)
	*p = x
	return p
}

func (x Game_Skills_Ranking_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Game_Skills_Ranking_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_dump_game_proto_enumTypes[5].Descriptor()
}

func (Game_Skills_Ranking_Type) Type() protoreflect.EnumType {
	return &file_dump_game_proto_enumTypes[5]
}

func (x Game_Skills_Ranking_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Game_Skills_Ranking_Type.Descriptor instead.
func (Game_Skills_Ranking_Type) EnumDescriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2, 4, 0, 0}
}

type Game_SkillsRanking_RankingType int32

const (
	Game_SkillsRanking_SKILLSRANKING_RANKINGTYPE_UNSPECIFIED                                     Game_SkillsRanking_RankingType = 0
	Game_SkillsRanking_SKILLSRANKING_RANKINGTYPE_COMBINED_HIGH_SCORES                            Game_SkillsRanking_RankingType = 1
	Game_SkillsRanking_SKILLSRANKING_RANKINGTYPE_ALTERNATING_HIGH_SCORES                         Game_SkillsRanking_RankingType = 2
	Game_SkillsRanking_SKILLSRANKING_RANKINGTYPE_HIGH_SCORE_FORMULA                              Game_SkillsRanking_RankingType = 3
	Game_SkillsRanking_SKILLSRANKING_RANKINGTYPE_ALTERNATING_HIGH_SCORES_LIMIT_2                 Game_SkillsRanking_RankingType = 4
	Game_SkillsRanking_SKILLSRANKING_RANKINGTYPE_STOP_TIME_SUM_FROM_HIGH_SCORE_MATCHES           Game_SkillsRanking_RankingType = 5
	Game_SkillsRanking_SKILLSRANKING_RANKINGTYPE_STOP_TIME_FROM_HIGH_SCORE_MATCH                 Game_SkillsRanking_RankingType = 6
	Game_SkillsRanking_SKILLSRANKING_RANKINGTYPE_ALTERNATING_HIGH_SCORES_THIRD                   Game_SkillsRanking_RankingType = 7
	Game_SkillsRanking_SKILLSRANKING_RANKINGTYPE_STOP_TIME_SUM_FROM_SECOND_HIGHEST_SCORE_MATCHES Game_SkillsRanking_RankingType = 8
	Game_SkillsRanking_SKILLSRANKING_RANKINGTYPE_STOP_TIME_SUM_FROM_THIRD_HIGHEST_SCORE_MATCHES  Game_SkillsRanking_RankingType = 9
	Game_SkillsRanking_SKILLSRANKING_RANKINGTYPE_SUM_THREE_DRIVER_ONE_PROGRAMMING                Game_SkillsRanking_RankingType = 10
	Game_SkillsRanking_SKILLSRANKING_RANKINGTYPE_HIGH_SCORES_SAME_TYPE                           Game_SkillsRanking_RankingType = 11
)

// Enum value maps for Game_SkillsRanking_RankingType.
var (
	Game_SkillsRanking_RankingType_name = map[int32]string{
		0:  "SKILLSRANKING_RANKINGTYPE_UNSPECIFIED",
		1:  "SKILLSRANKING_RANKINGTYPE_COMBINED_HIGH_SCORES",
		2:  "SKILLSRANKING_RANKINGTYPE_ALTERNATING_HIGH_SCORES",
		3:  "SKILLSRANKING_RANKINGTYPE_HIGH_SCORE_FORMULA",
		4:  "SKILLSRANKING_RANKINGTYPE_ALTERNATING_HIGH_SCORES_LIMIT_2",
		5:  "SKILLSRANKING_RANKINGTYPE_STOP_TIME_SUM_FROM_HIGH_SCORE_MATCHES",
		6:  "SKILLSRANKING_RANKINGTYPE_STOP_TIME_FROM_HIGH_SCORE_MATCH",
		7:  "SKILLSRANKING_RANKINGTYPE_ALTERNATING_HIGH_SCORES_THIRD",
		8:  "SKILLSRANKING_RANKINGTYPE_STOP_TIME_SUM_FROM_SECOND_HIGHEST_SCORE_MATCHES",
		9:  "SKILLSRANKING_RANKINGTYPE_STOP_TIME_SUM_FROM_THIRD_HIGHEST_SCORE_MATCHES",
		10: "SKILLSRANKING_RANKINGTYPE_SUM_THREE_DRIVER_ONE_PROGRAMMING",
		11: "SKILLSRANKING_RANKINGTYPE_HIGH_SCORES_SAME_TYPE",
	}
	Game_SkillsRanking_RankingType_value = map[string]int32{
		"SKILLSRANKING_RANKINGTYPE_UNSPECIFIED":                                     0,
		"SKILLSRANKING_RANKINGTYPE_COMBINED_HIGH_SCORES":                            1,
		"SKILLSRANKING_RANKINGTYPE_ALTERNATING_HIGH_SCORES":                         2,
		"SKILLSRANKING_RANKINGTYPE_HIGH_SCORE_FORMULA":                              3,
		"SKILLSRANKING_RANKINGTYPE_ALTERNATING_HIGH_SCORES_LIMIT_2":                 4,
		"SKILLSRANKING_RANKINGTYPE_STOP_TIME_SUM_FROM_HIGH_SCORE_MATCHES":           5,
		"SKILLSRANKING_RANKINGTYPE_STOP_TIME_FROM_HIGH_SCORE_MATCH":                 6,
		"SKILLSRANKING_RANKINGTYPE_ALTERNATING_HIGH_SCORES_THIRD":                   7,
		"SKILLSRANKING_RANKINGTYPE_STOP_TIME_SUM_FROM_SECOND_HIGHEST_SCORE_MATCHES": 8,
		"SKILLSRANKING_RANKINGTYPE_STOP_TIME_SUM_FROM_THIRD_HIGHEST_SCORE_MATCHES":  9,
		"SKILLSRANKING_RANKINGTYPE_SUM_THREE_DRIVER_ONE_PROGRAMMING":                10,
		"SKILLSRANKING_RANKINGTYPE_HIGH_SCORES_SAME_TYPE":                           11,
	}
)

func (x Game_SkillsRanking_RankingType) Enum() *Game_SkillsRanking_RankingType {
	p := new(Game_SkillsRanking_RankingType)
	*p = x
	return p
}

func (x Game_SkillsRanking_RankingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Game_SkillsRanking_RankingType) Descriptor() protoreflect.EnumDescriptor {
	return file_dump_game_proto_enumTypes[6].Descriptor()
}

func (Game_SkillsRanking_RankingType) Type() protoreflect.EnumType {
	return &file_dump_game_proto_enumTypes[6]
}

func (x Game_SkillsRanking_RankingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Game_SkillsRanking_RankingType.Descriptor instead.
func (Game_SkillsRanking_RankingType) EnumDescriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2, 5, 0}
}

type Game_SkillsRanking_SkillsType int32

const (
	Game_SkillsRanking_SKILLSRANKING_SKILLSTYPE_UNSPECIFIED Game_SkillsRanking_SkillsType = 0
	Game_SkillsRanking_SKILLSRANKING_SKILLSTYPE_PROGRAMMING Game_SkillsRanking_SkillsType = 1
	Game_SkillsRanking_SKILLSRANKING_SKILLSTYPE_DRIVER      Game_SkillsRanking_SkillsType = 2
)

// Enum value maps for Game_SkillsRanking_SkillsType.
var (
	Game_SkillsRanking_SkillsType_name = map[int32]string{
		0: "SKILLSRANKING_SKILLSTYPE_UNSPECIFIED",
		1: "SKILLSRANKING_SKILLSTYPE_PROGRAMMING",
		2: "SKILLSRANKING_SKILLSTYPE_DRIVER",
	}
	Game_SkillsRanking_SkillsType_value = map[string]int32{
		"SKILLSRANKING_SKILLSTYPE_UNSPECIFIED": 0,
		"SKILLSRANKING_SKILLSTYPE_PROGRAMMING": 1,
		"SKILLSRANKING_SKILLSTYPE_DRIVER":      2,
	}
)

func (x Game_SkillsRanking_SkillsType) Enum() *Game_SkillsRanking_SkillsType {
	p := new(Game_SkillsRanking_SkillsType)
	*p = x
	return p
}

func (x Game_SkillsRanking_SkillsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Game_SkillsRanking_SkillsType) Descriptor() protoreflect.EnumDescriptor {
	return file_dump_game_proto_enumTypes[7].Descriptor()
}

func (Game_SkillsRanking_SkillsType) Type() protoreflect.EnumType {
	return &file_dump_game_proto_enumTypes[7]
}

func (x Game_SkillsRanking_SkillsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Game_SkillsRanking_SkillsType.Descriptor instead.
func (Game_SkillsRanking_SkillsType) EnumDescriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2, 5, 1}
}

type GameWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Auth          []byte                 `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameWrapper) Reset() {
	*x = GameWrapper{}
	mi := &file_dump_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameWrapper) ProtoMessage() {}

func (x *GameWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_dump_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameWrapper.ProtoReflect.Descriptor instead.
func (*GameWrapper) Descriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameWrapper) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GameWrapper) GetAuth() []byte {
	if x != nil {
		return x.Auth
	}
	return nil
}

type TournamentRound struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	Type              TournamentRound_RoundType   `protobuf:"varint,1,opt,name=type,proto3,enum=TournamentRound_RoundType" json:"type,omitempty"`
	NumTeams          uint32                      `protobuf:"varint,2,opt,name=numTeams,proto3" json:"numTeams,omitempty"`
	DisplayName       string                      `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
	RoundNum          uint32                      `protobuf:"varint,4,opt,name=roundNum,proto3" json:"roundNum,omitempty"`
	TeamsPerAlliance  uint32                      `protobuf:"varint,5,opt,name=teamsPerAlliance,proto3" json:"teamsPerAlliance,omitempty"`
	AlliancesPerMatch uint32                      `protobuf:"varint,6,opt,name=alliancesPerMatch,proto3" json:"alliancesPerMatch,omitempty"`
	Scoring           *Game_Scoring               `protobuf:"bytes,7,opt,name=scoring,proto3" json:"scoring,omitempty"`
	Rankings          TournamentRound_RankingType `protobuf:"varint,8,opt,name=rankings,proto3,enum=TournamentRound_RankingType" json:"rankings,omitempty"`
	MatchTimes        []*Game_MatchTimeEntry      `protobuf:"bytes,9,rep,name=matchTimes,proto3" json:"matchTimes,omitempty"`
	Sounds            []*Game_MatchSound          `protobuf:"bytes,10,rep,name=sounds,proto3" json:"sounds,omitempty"`
	LeagueRankings    TournamentRound_RankingType `protobuf:"varint,11,opt,name=leagueRankings,proto3,enum=TournamentRound_RankingType" json:"leagueRankings,omitempty"`
	NumAlliances      uint32                      `protobuf:"varint,12,opt,name=numAlliances,proto3" json:"numAlliances,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TournamentRound) Reset() {
	*x = TournamentRound{}
	mi := &file_dump_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentRound) ProtoMessage() {}

func (x *TournamentRound) ProtoReflect() protoreflect.Message {
	mi := &file_dump_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentRound.ProtoReflect.Descriptor instead.
func (*TournamentRound) Descriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{1}
}

func (x *TournamentRound) GetType() TournamentRound_RoundType {
	if x != nil {
		return x.Type
	}
	return TournamentRound_TOURNAMENTROUND_ROUNDTYPE_UNSPECIFIED
}

func (x *TournamentRound) GetNumTeams() uint32 {
	if x != nil {
		return x.NumTeams
	}
	return 0
}

func (x *TournamentRound) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *TournamentRound) GetRoundNum() uint32 {
	if x != nil {
		return x.RoundNum
	}
	return 0
}

func (x *TournamentRound) GetTeamsPerAlliance() uint32 {
	if x != nil {
		return x.TeamsPerAlliance
	}
	return 0
}

func (x *TournamentRound) GetAlliancesPerMatch() uint32 {
	if x != nil {
		return x.AlliancesPerMatch
	}
	return 0
}

func (x *TournamentRound) GetScoring() *Game_Scoring {
	if x != nil {
		return x.Scoring
	}
	return nil
}

func (x *TournamentRound) GetRankings() TournamentRound_RankingType {
	if x != nil {
		return x.Rankings
	}
	return TournamentRound_TOURNAMENTROUND_RANKINGTYPE_UNSPECIFIED
}

func (x *TournamentRound) GetMatchTimes() []*Game_MatchTimeEntry {
	if x != nil {
		return x.MatchTimes
	}
	return nil
}

func (x *TournamentRound) GetSounds() []*Game_MatchSound {
	if x != nil {
		return x.Sounds
	}
	return nil
}

func (x *TournamentRound) GetLeagueRankings() TournamentRound_RankingType {
	if x != nil {
		return x.LeagueRankings
	}
	return TournamentRound_TOURNAMENTROUND_RANKINGTYPE_UNSPECIFIED
}

func (x *TournamentRound) GetNumAlliances() uint32 {
	if x != nil {
		return x.NumAlliances
	}
	return 0
}

type Game struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion                uint32                 `protobuf:"varint,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Uuid                      string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Version                   uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Program                   Game_VexProgram        `protobuf:"varint,4,opt,name=program,proto3,enum=Game_VexProgram" json:"program,omitempty"`
	Name                      string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Season                    string                 `protobuf:"bytes,6,opt,name=season,proto3" json:"season,omitempty"`
	DefaultSounds             []*Game_MatchSound     `protobuf:"bytes,7,rep,name=defaultSounds,proto3" json:"defaultSounds,omitempty"`
	DefaultScoring            *Game_Scoring          `protobuf:"bytes,8,opt,name=defaultScoring,proto3" json:"defaultScoring,omitempty"`
	DefaultMatchTimes         []*Game_MatchTimeEntry `protobuf:"bytes,9,rep,name=defaultMatchTimes,proto3" json:"defaultMatchTimes,omitempty"`
	Rounds                    []*TournamentRound     `protobuf:"bytes,10,rep,name=rounds,proto3" json:"rounds,omitempty"`
	Skills                    []*Game_Skills         `protobuf:"bytes,11,rep,name=skills,proto3" json:"skills,omitempty"`
	InterfaceXml              []byte                 `protobuf:"bytes,12,opt,name=interfaceXml,proto3" json:"interfaceXml,omitempty"`
	SkillsRankings            []*Game_SkillsRanking  `protobuf:"bytes,13,rep,name=skillsRankings,proto3" json:"skillsRankings,omitempty"`
	SkillsInitialObjectStates []*Game_ScoreObject    `protobuf:"bytes,14,rep,name=skillsInitialObjectStates,proto3" json:"skillsInitialObjectStates,omitempty"`
	ScoringModule             string                 `protobuf:"bytes,15,opt,name=scoringModule,proto3" json:"scoringModule,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_dump_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_dump_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2}
}

func (x *Game) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *Game) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Game) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Game) GetProgram() Game_VexProgram {
	if x != nil {
		return x.Program
	}
	return Game_GAME_VEXPROGRAM_UNSPECIFIED
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

func (x *Game) GetDefaultSounds() []*Game_MatchSound {
	if x != nil {
		return x.DefaultSounds
	}
	return nil
}

func (x *Game) GetDefaultScoring() *Game_Scoring {
	if x != nil {
		return x.DefaultScoring
	}
	return nil
}

func (x *Game) GetDefaultMatchTimes() []*Game_MatchTimeEntry {
	if x != nil {
		return x.DefaultMatchTimes
	}
	return nil
}

func (x *Game) GetRounds() []*TournamentRound {
	if x != nil {
		return x.Rounds
	}
	return nil
}

func (x *Game) GetSkills() []*Game_Skills {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Game) GetInterfaceXml() []byte {
	if x != nil {
		return x.InterfaceXml
	}
	return nil
}

func (x *Game) GetSkillsRankings() []*Game_SkillsRanking {
	if x != nil {
		return x.SkillsRankings
	}
	return nil
}

func (x *Game) GetSkillsInitialObjectStates() []*Game_ScoreObject {
	if x != nil {
		return x.SkillsInitialObjectStates
	}
	return nil
}

func (x *Game) GetScoringModule() string {
	if x != nil {
		return x.ScoringModule
	}
	return ""
}

type Game_Scoring struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MatchScoreFormula    string                 `protobuf:"bytes,1,opt,name=matchScoreFormula,proto3" json:"matchScoreFormula,omitempty"`
	AllianceScoreFormula string                 `protobuf:"bytes,2,opt,name=allianceScoreFormula,proto3" json:"allianceScoreFormula,omitempty"`
	TeamScoreFormula     string                 `protobuf:"bytes,3,opt,name=teamScoreFormula,proto3" json:"teamScoreFormula,omitempty"`
	ScoringConstraints   []string               `protobuf:"bytes,4,rep,name=scoringConstraints,proto3" json:"scoringConstraints,omitempty"`
	ApFormula            string                 `protobuf:"bytes,10,opt,name=apFormula,proto3" json:"apFormula,omitempty"`
	WpFormula            string                 `protobuf:"bytes,11,opt,name=wpFormula,proto3" json:"wpFormula,omitempty"`
	SpFormula            string                 `protobuf:"bytes,12,opt,name=spFormula,proto3" json:"spFormula,omitempty"`
	AwpFormula           string                 `protobuf:"bytes,13,opt,name=awpFormula,proto3" json:"awpFormula,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Game_Scoring) Reset() {
	*x = Game_Scoring{}
	mi := &file_dump_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game_Scoring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game_Scoring) ProtoMessage() {}

func (x *Game_Scoring) ProtoReflect() protoreflect.Message {
	mi := &file_dump_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game_Scoring.ProtoReflect.Descriptor instead.
func (*Game_Scoring) Descriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Game_Scoring) GetMatchScoreFormula() string {
	if x != nil {
		return x.MatchScoreFormula
	}
	return ""
}

func (x *Game_Scoring) GetAllianceScoreFormula() string {
	if x != nil {
		return x.AllianceScoreFormula
	}
	return ""
}

func (x *Game_Scoring) GetTeamScoreFormula() string {
	if x != nil {
		return x.TeamScoreFormula
	}
	return ""
}

func (x *Game_Scoring) GetScoringConstraints() []string {
	if x != nil {
		return x.ScoringConstraints
	}
	return nil
}

func (x *Game_Scoring) GetApFormula() string {
	if x != nil {
		return x.ApFormula
	}
	return ""
}

func (x *Game_Scoring) GetWpFormula() string {
	if x != nil {
		return x.WpFormula
	}
	return ""
}

func (x *Game_Scoring) GetSpFormula() string {
	if x != nil {
		return x.SpFormula
	}
	return ""
}

func (x *Game_Scoring) GetAwpFormula() string {
	if x != nil {
		return x.AwpFormula
	}
	return ""
}

type Game_MatchTimeEntry struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Seconds       int32                         `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Type          Game_MatchTimeEntry_BlockType `protobuf:"varint,2,opt,name=type,proto3,enum=Game_MatchTimeEntry_BlockType" json:"type,omitempty"`
	Name          string                        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game_MatchTimeEntry) Reset() {
	*x = Game_MatchTimeEntry{}
	mi := &file_dump_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game_MatchTimeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game_MatchTimeEntry) ProtoMessage() {}

func (x *Game_MatchTimeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dump_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game_MatchTimeEntry.ProtoReflect.Descriptor instead.
func (*Game_MatchTimeEntry) Descriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Game_MatchTimeEntry) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Game_MatchTimeEntry) GetType() Game_MatchTimeEntry_BlockType {
	if x != nil {
		return x.Type
	}
	return Game_MatchTimeEntry_MATCHTIMEENTRY_BLOCKTYPE_UNSPECIFIED
}

func (x *Game_MatchTimeEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Game_MatchSound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Cause         string                 `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=fileName,proto3" json:"fileName,omitempty"`
	TimeLeft      uint32                 `protobuf:"varint,4,opt,name=timeLeft,proto3" json:"timeLeft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game_MatchSound) Reset() {
	*x = Game_MatchSound{}
	mi := &file_dump_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game_MatchSound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game_MatchSound) ProtoMessage() {}

func (x *Game_MatchSound) ProtoReflect() protoreflect.Message {
	mi := &file_dump_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game_MatchSound.ProtoReflect.Descriptor instead.
func (*Game_MatchSound) Descriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Game_MatchSound) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Game_MatchSound) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *Game_MatchSound) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Game_MatchSound) GetTimeLeft() uint32 {
	if x != nil {
		return x.TimeLeft
	}
	return 0
}

type Game_ScoreObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Val           int32                  `protobuf:"varint,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game_ScoreObject) Reset() {
	*x = Game_ScoreObject{}
	mi := &file_dump_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game_ScoreObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game_ScoreObject) ProtoMessage() {}

func (x *Game_ScoreObject) ProtoReflect() protoreflect.Message {
	mi := &file_dump_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game_ScoreObject.ProtoReflect.Descriptor instead.
func (*Game_ScoreObject) Descriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Game_ScoreObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game_ScoreObject) GetVal() int32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type Game_Skills struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	ObsoleteRobotSkillsDuration uint32                 `protobuf:"varint,1,opt,name=obsolete_robotSkillsDuration,json=obsoleteRobotSkillsDuration,proto3" json:"obsolete_robotSkillsDuration,omitempty"`
	ObsoleteProgSkillsDuration  uint32                 `protobuf:"varint,2,opt,name=obsolete_progSkillsDuration,json=obsoleteProgSkillsDuration,proto3" json:"obsolete_progSkillsDuration,omitempty"`
	Scoring                     *Game_Scoring          `protobuf:"bytes,3,opt,name=scoring,proto3" json:"scoring,omitempty"`
	Rankings                    []*Game_Skills_Ranking `protobuf:"bytes,4,rep,name=rankings,proto3" json:"rankings,omitempty"`
	Name                        string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	SkillsTimes                 []*Game_MatchTimeEntry `protobuf:"bytes,9,rep,name=skillsTimes,proto3" json:"skillsTimes,omitempty"`
	Sounds                      []*Game_MatchSound     `protobuf:"bytes,10,rep,name=sounds,proto3" json:"sounds,omitempty"`
	SkillsType                  Game_Skills_SkillsType `protobuf:"varint,11,opt,name=skillsType,proto3,enum=Game_Skills_SkillsType" json:"skillsType,omitempty"`
	MaxAttempts                 uint32                 `protobuf:"varint,12,opt,name=maxAttempts,proto3" json:"maxAttempts,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Game_Skills) Reset() {
	*x = Game_Skills{}
	mi := &file_dump_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game_Skills) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game_Skills) ProtoMessage() {}

func (x *Game_Skills) ProtoReflect() protoreflect.Message {
	mi := &file_dump_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game_Skills.ProtoReflect.Descriptor instead.
func (*Game_Skills) Descriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2, 4}
}

func (x *Game_Skills) GetObsoleteRobotSkillsDuration() uint32 {
	if x != nil {
		return x.ObsoleteRobotSkillsDuration
	}
	return 0
}

func (x *Game_Skills) GetObsoleteProgSkillsDuration() uint32 {
	if x != nil {
		return x.ObsoleteProgSkillsDuration
	}
	return 0
}

func (x *Game_Skills) GetScoring() *Game_Scoring {
	if x != nil {
		return x.Scoring
	}
	return nil
}

func (x *Game_Skills) GetRankings() []*Game_Skills_Ranking {
	if x != nil {
		return x.Rankings
	}
	return nil
}

func (x *Game_Skills) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game_Skills) GetSkillsTimes() []*Game_MatchTimeEntry {
	if x != nil {
		return x.SkillsTimes
	}
	return nil
}

func (x *Game_Skills) GetSounds() []*Game_MatchSound {
	if x != nil {
		return x.Sounds
	}
	return nil
}

func (x *Game_Skills) GetSkillsType() Game_Skills_SkillsType {
	if x != nil {
		return x.SkillsType
	}
	return Game_Skills_SKILLS_SKILLSTYPE_UNSPECIFIED
}

func (x *Game_Skills) GetMaxAttempts() uint32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

type Game_SkillsRanking struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	RankingType   Game_SkillsRanking_RankingType `protobuf:"varint,1,opt,name=rankingType,proto3,enum=Game_SkillsRanking_RankingType" json:"rankingType,omitempty"`
	SkillsType    Game_SkillsRanking_SkillsType  `protobuf:"varint,2,opt,name=skillsType,proto3,enum=Game_SkillsRanking_SkillsType" json:"skillsType,omitempty"`
	Formula       string                         `protobuf:"bytes,3,opt,name=formula,proto3" json:"formula,omitempty"`
	NumScores     uint32                         `protobuf:"varint,4,opt,name=num_scores,json=numScores,proto3" json:"num_scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game_SkillsRanking) Reset() {
	*x = Game_SkillsRanking{}
	mi := &file_dump_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game_SkillsRanking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game_SkillsRanking) ProtoMessage() {}

func (x *Game_SkillsRanking) ProtoReflect() protoreflect.Message {
	mi := &file_dump_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game_SkillsRanking.ProtoReflect.Descriptor instead.
func (*Game_SkillsRanking) Descriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2, 5}
}

func (x *Game_SkillsRanking) GetRankingType() Game_SkillsRanking_RankingType {
	if x != nil {
		return x.RankingType
	}
	return Game_SkillsRanking_SKILLSRANKING_RANKINGTYPE_UNSPECIFIED
}

func (x *Game_SkillsRanking) GetSkillsType() Game_SkillsRanking_SkillsType {
	if x != nil {
		return x.SkillsType
	}
	return Game_SkillsRanking_SKILLSRANKING_SKILLSTYPE_UNSPECIFIED
}

func (x *Game_SkillsRanking) GetFormula() string {
	if x != nil {
		return x.Formula
	}
	return ""
}

func (x *Game_SkillsRanking) GetNumScores() uint32 {
	if x != nil {
		return x.NumScores
	}
	return 0
}

type Game_Skills_Ranking struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          Game_Skills_Ranking_Type `protobuf:"varint,1,opt,name=type,proto3,enum=Game_Skills_Ranking_Type" json:"type,omitempty"`
	Formula       string                   `protobuf:"bytes,2,opt,name=formula,proto3" json:"formula,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game_Skills_Ranking) Reset() {
	*x = Game_Skills_Ranking{}
	mi := &file_dump_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game_Skills_Ranking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game_Skills_Ranking) ProtoMessage() {}

func (x *Game_Skills_Ranking) ProtoReflect() protoreflect.Message {
	mi := &file_dump_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game_Skills_Ranking.ProtoReflect.Descriptor instead.
func (*Game_Skills_Ranking) Descriptor() ([]byte, []int) {
	return file_dump_game_proto_rawDescGZIP(), []int{2, 4, 0}
}

func (x *Game_Skills_Ranking) GetType() Game_Skills_Ranking_Type {
	if x != nil {
		return x.Type
	}
	return Game_Skills_Ranking_RANKING_TYPE_UNSPECIFIED
}

func (x *Game_Skills_Ranking) GetFormula() string {
	if x != nil {
		return x.Formula
	}
	return ""
}

var File_dump_game_proto protoreflect.FileDescriptor

const file_dump_game_proto_rawDesc = "" +
	"\n" +
	"\x0fdump/game.proto\"5\n" +
	"\vGameWrapper\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04auth\x18\x02 \x01(\fR\x04auth\"\xcd\r\n" +
	"\x0fTournamentRound\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.TournamentRound.RoundTypeR\x04type\x12\x1a\n" +
	"\bnumTeams\x18\x02 \x01(\rR\bnumTeams\x12 \n" +
	"\vdisplayName\x18\x03 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\broundNum\x18\x04 \x01(\rR\broundNum\x12*\n" +
	"\x10teamsPerAlliance\x18\x05 \x01(\rR\x10teamsPerAlliance\x12,\n" +
	"\x11alliancesPerMatch\x18\x06 \x01(\rR\x11alliancesPerMatch\x12'\n" +
	"\ascoring\x18\a \x01(\v2\r.Game.ScoringR\ascoring\x128\n" +
	"\brankings\x18\b \x01(\x0e2\x1c.TournamentRound.RankingTypeR\brankings\x124\n" +
	"\n" +
	"matchTimes\x18\t \x03(\v2\x14.Game.MatchTimeEntryR\n" +
	"matchTimes\x12(\n" +
	"\x06sounds\x18\n" +
	" \x03(\v2\x10.Game.MatchSoundR\x06sounds\x12D\n" +
	"\x0eleagueRankings\x18\v \x01(\x0e2\x1c.TournamentRound.RankingTypeR\x0eleagueRankings\x12\"\n" +
	"\fnumAlliances\x18\f \x01(\rR\fnumAlliances\"\x91\x02\n" +
	"\tRoundType\x12)\n" +
	"%TOURNAMENTROUND_ROUNDTYPE_UNSPECIFIED\x10\x00\x12,\n" +
	"(TOURNAMENTROUND_ROUNDTYPE_RANDOM_MATCHES\x10\x01\x12/\n" +
	"+TOURNAMENTROUND_ROUNDTYPE_SINGLE_ELIM_WIN_2\x10\x02\x12)\n" +
	"%TOURNAMENTROUND_ROUNDTYPE_ROUND_ROBIN\x10\x03\x12#\n" +
	"\x1fTOURNAMENTROUND_ROUNDTYPE_TOP_N\x10\x04\x12*\n" +
	"&TOURNAMENTROUND_ROUNDTYPE_TIERED_TOP_N\x10\x05\"\x94\a\n" +
	"\vRankingType\x12+\n" +
	"'TOURNAMENTROUND_RANKINGTYPE_UNSPECIFIED\x10\x00\x12+\n" +
	"'TOURNAMENTROUND_RANKINGTYPE_NO_RANKINGS\x10\x01\x12%\n" +
	"!TOURNAMENTROUND_RANKINGTYPE_WP_SP\x10\x02\x12-\n" +
	")TOURNAMENTROUND_RANKINGTYPE_WIN_PCT_WP_SP\x10\x03\x120\n" +
	",TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_3_OF_4\x10\x04\x124\n" +
	"0TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_PREV_ROUND\x10\x05\x125\n" +
	"1TOURNAMENTROUND_RANKINGTYPE_WP_HEADTOHEAD_TOT_PTS\x10\x06\x125\n" +
	"1TOURNAMENTROUND_RANKINGTYPE_AVG_SCORE_HIGH_SCORES\x10\a\x12.\n" +
	"*TOURNAMENTROUND_RANKINGTYPE_AVG_PTS_3_OF_4\x10\b\x12(\n" +
	"$TOURNAMENTROUND_RANKINGTYPE_WP_AP_SP\x10\t\x120\n" +
	",TOURNAMENTROUND_RANKINGTYPE_WIN_PCT_WP_AP_SP\x10\n" +
	"\x12,\n" +
	"(TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_WP\x10\v\x12,\n" +
	"(TOURNAMENTROUND_RANKINGTYPE_AVG_WP_AP_SP\x10\f\x12<\n" +
	"8TOURNAMENTROUND_RANKINGTYPE_AVG_WP_AVG_SCORE_HIGH_SCORES\x10\r\x12>\n" +
	":TOURNAMENTROUND_RANKINGTYPE_TOTAL_PTS_OVERALL_SCORE_DROP_1\x10\x0e\x12'\n" +
	"#TOURNAMENTROUND_RANKINGTYPE_AVG_PTS\x10\x0f\x123\n" +
	"/TOURNAMENTROUND_RANKINGTYPE_AVG_PTS_DROP_1_OF_6\x10\x10\x12;\n" +
	"7TOURNAMENTROUND_RANKINGTYPE_AVG_PTS_3_OF_4_KEEP_NO_SHOW\x10\x11\"\xa1\x1c\n" +
	"\x04Game\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\rR\n" +
	"apiVersion\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12*\n" +
	"\aprogram\x18\x04 \x01(\x0e2\x10.Game.VexProgramR\aprogram\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06season\x18\x06 \x01(\tR\x06season\x126\n" +
	"\rdefaultSounds\x18\a \x03(\v2\x10.Game.MatchSoundR\rdefaultSounds\x125\n" +
	"\x0edefaultScoring\x18\b \x01(\v2\r.Game.ScoringR\x0edefaultScoring\x12B\n" +
	"\x11defaultMatchTimes\x18\t \x03(\v2\x14.Game.MatchTimeEntryR\x11defaultMatchTimes\x12(\n" +
	"\x06rounds\x18\n" +
	" \x03(\v2\x10.TournamentRoundR\x06rounds\x12$\n" +
	"\x06skills\x18\v \x03(\v2\f.Game.SkillsR\x06skills\x12\"\n" +
	"\finterfaceXml\x18\f \x01(\fR\finterfaceXml\x12;\n" +
	"\x0eskillsRankings\x18\r \x03(\v2\x13.Game.SkillsRankingR\x0eskillsRankings\x12O\n" +
	"\x19skillsInitialObjectStates\x18\x0e \x03(\v2\x11.Game.ScoreObjectR\x19skillsInitialObjectStates\x12$\n" +
	"\rscoringModule\x18\x0f \x01(\tR\rscoringModule\x1a\xc1\x02\n" +
	"\aScoring\x12,\n" +
	"\x11matchScoreFormula\x18\x01 \x01(\tR\x11matchScoreFormula\x122\n" +
	"\x14allianceScoreFormula\x18\x02 \x01(\tR\x14allianceScoreFormula\x12*\n" +
	"\x10teamScoreFormula\x18\x03 \x01(\tR\x10teamScoreFormula\x12.\n" +
	"\x12scoringConstraints\x18\x04 \x03(\tR\x12scoringConstraints\x12\x1c\n" +
	"\tapFormula\x18\n" +
	" \x01(\tR\tapFormula\x12\x1c\n" +
	"\twpFormula\x18\v \x01(\tR\twpFormula\x12\x1c\n" +
	"\tspFormula\x18\f \x01(\tR\tspFormula\x12\x1e\n" +
	"\n" +
	"awpFormula\x18\r \x01(\tR\n" +
	"awpFormula\x1a\xf1\x02\n" +
	"\x0eMatchTimeEntry\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x05R\aseconds\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.Game.MatchTimeEntry.BlockTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xfc\x01\n" +
	"\tBlockType\x12(\n" +
	"$MATCHTIMEENTRY_BLOCKTYPE_UNSPECIFIED\x10\x00\x12'\n" +
	"#MATCHTIMEENTRY_BLOCKTYPE_TIMER_ONLY\x10\x01\x12'\n" +
	"#MATCHTIMEENTRY_BLOCKTYPE_AUTONOMOUS\x10\x02\x12(\n" +
	"$MATCHTIMEENTRY_BLOCKTYPE_DRIVER_CTRL\x10\x03\x12\"\n" +
	"\x1eMATCHTIMEENTRY_BLOCKTYPE_PAUSE\x10\x04\x12%\n" +
	"!MATCHTIMEENTRY_BLOCKTYPE_PRESTART\x10\x05\x1ap\n" +
	"\n" +
	"MatchSound\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x14\n" +
	"\x05cause\x18\x02 \x01(\tR\x05cause\x12\x1a\n" +
	"\bfileName\x18\x03 \x01(\tR\bfileName\x12\x1a\n" +
	"\btimeLeft\x18\x04 \x01(\rR\btimeLeft\x1a3\n" +
	"\vScoreObject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03val\x18\x02 \x01(\x05R\x03val\x1a\x92\x06\n" +
	"\x06Skills\x12A\n" +
	"\x1cobsolete_robotSkillsDuration\x18\x01 \x01(\rR\x1bobsoleteRobotSkillsDuration\x12?\n" +
	"\x1bobsolete_progSkillsDuration\x18\x02 \x01(\rR\x1aobsoleteProgSkillsDuration\x12'\n" +
	"\ascoring\x18\x03 \x01(\v2\r.Game.ScoringR\ascoring\x120\n" +
	"\brankings\x18\x04 \x03(\v2\x14.Game.Skills.RankingR\brankings\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x126\n" +
	"\vskillsTimes\x18\t \x03(\v2\x14.Game.MatchTimeEntryR\vskillsTimes\x12(\n" +
	"\x06sounds\x18\n" +
	" \x03(\v2\x10.Game.MatchSoundR\x06sounds\x127\n" +
	"\n" +
	"skillsType\x18\v \x01(\x0e2\x17.Game.Skills.SkillsTypeR\n" +
	"skillsType\x12 \n" +
	"\vmaxAttempts\x18\f \x01(\rR\vmaxAttempts\x1a\xe5\x01\n" +
	"\aRanking\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.Game.Skills.Ranking.TypeR\x04type\x12\x18\n" +
	"\aformula\x18\x02 \x01(\tR\aformula\"\x90\x01\n" +
	"\x04Type\x12\x1c\n" +
	"\x18RANKING_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RANKING_TYPE_HIGH_SCORES\x10\x01\x12#\n" +
	"\x1fRANKING_TYPE_HIGH_SCORE_FORMULA\x10\x02\x12'\n" +
	"#RANKING_TYPE_TOTAL_POINTS_RECURSIVE\x10\x03\"p\n" +
	"\n" +
	"SkillsType\x12!\n" +
	"\x1dSKILLS_SKILLSTYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSKILLS_SKILLSTYPE_PROGRAMMING\x10\x01\x12\x1c\n" +
	"\x18SKILLS_SKILLSTYPE_DRIVER\x10\x02\x1a\xbd\b\n" +
	"\rSkillsRanking\x12A\n" +
	"\vrankingType\x18\x01 \x01(\x0e2\x1f.Game.SkillsRanking.RankingTypeR\vrankingType\x12>\n" +
	"\n" +
	"skillsType\x18\x02 \x01(\x0e2\x1e.Game.SkillsRanking.SkillsTypeR\n" +
	"skillsType\x12\x18\n" +
	"\aformula\x18\x03 \x01(\tR\aformula\x12\x1d\n" +
	"\n" +
	"num_scores\x18\x04 \x01(\rR\tnumScores\"\xe7\x05\n" +
	"\vRankingType\x12)\n" +
	"%SKILLSRANKING_RANKINGTYPE_UNSPECIFIED\x10\x00\x122\n" +
	".SKILLSRANKING_RANKINGTYPE_COMBINED_HIGH_SCORES\x10\x01\x125\n" +
	"1SKILLSRANKING_RANKINGTYPE_ALTERNATING_HIGH_SCORES\x10\x02\x120\n" +
	",SKILLSRANKING_RANKINGTYPE_HIGH_SCORE_FORMULA\x10\x03\x12=\n" +
	"9SKILLSRANKING_RANKINGTYPE_ALTERNATING_HIGH_SCORES_LIMIT_2\x10\x04\x12C\n" +
	"?SKILLSRANKING_RANKINGTYPE_STOP_TIME_SUM_FROM_HIGH_SCORE_MATCHES\x10\x05\x12=\n" +
	"9SKILLSRANKING_RANKINGTYPE_STOP_TIME_FROM_HIGH_SCORE_MATCH\x10\x06\x12;\n" +
	"7SKILLSRANKING_RANKINGTYPE_ALTERNATING_HIGH_SCORES_THIRD\x10\a\x12M\n" +
	"ISKILLSRANKING_RANKINGTYPE_STOP_TIME_SUM_FROM_SECOND_HIGHEST_SCORE_MATCHES\x10\b\x12L\n" +
	"HSKILLSRANKING_RANKINGTYPE_STOP_TIME_SUM_FROM_THIRD_HIGHEST_SCORE_MATCHES\x10\t\x12>\n" +
	":SKILLSRANKING_RANKINGTYPE_SUM_THREE_DRIVER_ONE_PROGRAMMING\x10\n" +
	"\x123\n" +
	"/SKILLSRANKING_RANKINGTYPE_HIGH_SCORES_SAME_TYPE\x10\v\"\x85\x01\n" +
	"\n" +
	"SkillsType\x12(\n" +
	"$SKILLSRANKING_SKILLSTYPE_UNSPECIFIED\x10\x00\x12(\n" +
	"$SKILLSRANKING_SKILLSTYPE_PROGRAMMING\x10\x01\x12#\n" +
	"\x1fSKILLSRANKING_SKILLSTYPE_DRIVER\x10\x02\"\xe3\x01\n" +
	"\n" +
	"VexProgram\x12\x1f\n" +
	"\x1bGAME_VEXPROGRAM_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13GAME_VEXPROGRAM_VRC\x10\n" +
	"\x12\x18\n" +
	"\x14GAME_VEXPROGRAM_VEXU\x10\x14\x12\x19\n" +
	"\x15GAME_VEXPROGRAM_VEXIQ\x10\x1e\x12\x19\n" +
	"\x15GAME_VEXPROGRAM_VEXAI\x10(\x12\x18\n" +
	"\x14GAME_VEXPROGRAM_RADC\x102\x12\x18\n" +
	"\x14GAME_VEXPROGRAM_BELL\x10<\x12\x17\n" +
	"\x13GAME_VEXPROGRAM_TSA\x10dB\x10Z\x0einternal/protob\x06proto3"

var (
	file_dump_game_proto_rawDescOnce sync.Once
	file_dump_game_proto_rawDescData []byte
)

func file_dump_game_proto_rawDescGZIP() []byte {
	file_dump_game_proto_rawDescOnce.Do(func() {
		file_dump_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dump_game_proto_rawDesc), len(file_dump_game_proto_rawDesc)))
	})
	return file_dump_game_proto_rawDescData
}

var file_dump_game_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_dump_game_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_dump_game_proto_goTypes = []any{
	(TournamentRound_RoundType)(0),      // 0: TournamentRound.RoundType
	(TournamentRound_RankingType)(0),    // 1: TournamentRound.RankingType
	(Game_VexProgram)(0),                // 2: Game.VexProgram
	(Game_MatchTimeEntry_BlockType)(0),  // 3: Game.MatchTimeEntry.BlockType
	(Game_Skills_SkillsType)(0),         // 4: Game.Skills.SkillsType
	(Game_Skills_Ranking_Type)(0),       // 5: Game.Skills.Ranking.Type
	(Game_SkillsRanking_RankingType)(0), // 6: Game.SkillsRanking.RankingType
	(Game_SkillsRanking_SkillsType)(0),  // 7: Game.SkillsRanking.SkillsType
	(*GameWrapper)(nil),                 // 8: GameWrapper
	(*TournamentRound)(nil),             // 9: TournamentRound
	(*Game)(nil),                        // 10: Game
	(*Game_Scoring)(nil),                // 11: Game.Scoring
	(*Game_MatchTimeEntry)(nil),         // 12: Game.MatchTimeEntry
	(*Game_MatchSound)(nil),             // 13: Game.MatchSound
	(*Game_ScoreObject)(nil),            // 14: Game.ScoreObject
	(*Game_Skills)(nil),                 // 15: Game.Skills
	(*Game_SkillsRanking)(nil),          // 16: Game.SkillsRanking
	(*Game_Skills_Ranking)(nil),         // 17: Game.Skills.Ranking
}
var file_dump_game_proto_depIdxs = []int32{
	0,  // 0: TournamentRound.type:type_name -> TournamentRound.RoundType
	11, // 1: TournamentRound.scoring:type_name -> Game.Scoring
	1,  // 2: TournamentRound.rankings:type_name -> TournamentRound.RankingType
	12, // 3: TournamentRound.matchTimes:type_name -> Game.MatchTimeEntry
	13, // 4: TournamentRound.sounds:type_name -> Game.MatchSound
	1,  // 5: TournamentRound.leagueRankings:type_name -> TournamentRound.RankingType
	2,  // 6: Game.program:type_name -> Game.VexProgram
	13, // 7: Game.defaultSounds:type_name -> Game.MatchSound
	11, // 8: Game.defaultScoring:type_name -> Game.Scoring
	12, // 9: Game.defaultMatchTimes:type_name -> Game.MatchTimeEntry
	9,  // 10: Game.rounds:type_name -> TournamentRound
	15, // 11: Game.skills:type_name -> Game.Skills
	16, // 12: Game.skillsRankings:type_name -> Game.SkillsRanking
	14, // 13: Game.skillsInitialObjectStates:type_name -> Game.ScoreObject
	3,  // 14: Game.MatchTimeEntry.type:type_name -> Game.MatchTimeEntry.BlockType
	11, // 15: Game.Skills.scoring:type_name -> Game.Scoring
	17, // 16: Game.Skills.rankings:type_name -> Game.Skills.Ranking
	12, // 17: Game.Skills.skillsTimes:type_name -> Game.MatchTimeEntry
	13, // 18: Game.Skills.sounds:type_name -> Game.MatchSound
	4,  // 19: Game.Skills.skillsType:type_name -> Game.Skills.SkillsType
	6,  // 20: Game.SkillsRanking.rankingType:type_name -> Game.SkillsRanking.RankingType
	7,  // 21: Game.SkillsRanking.skillsType:type_name -> Game.SkillsRanking.SkillsType
	5,  // 22: Game.Skills.Ranking.type:type_name -> Game.Skills.Ranking.Type
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_dump_game_proto_init() }
func file_dump_game_proto_init() {
	if File_dump_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dump_game_proto_rawDesc), len(file_dump_game_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dump_game_proto_goTypes,
		DependencyIndexes: file_dump_game_proto_depIdxs,
		EnumInfos:         file_dump_game_proto_enumTypes,
		MessageInfos:      file_dump_game_proto_msgTypes,
	}.Build()
	File_dump_game_proto = out.File
	file_dump_game_proto_goTypes = nil
	file_dump_game_proto_depIdxs = nil
}
